### PR TITLE
Always use core::arch

### PR DESCRIPTION
**Pull request by niklasf**
Hi, does this crate have a policy for the minimum supported Rust version? It would be a fair bit lighter after dropping support for Rust 1.26.x. I did not delete the feature flags for bc, although I guess no outside crate should set them.

### CODE REVIEW

**Comment by gz** [comment]
Hi, Thanks for submitting this pull request. Always happy to remove bit-cruft. 

Because this crate is transitively used quite a bit, ideally there would have some data on how much rust <1.26 is still in use but I'm not aware of any data on this.

**Comment by niklasf** [comment]
Not sure if anyone has usage data. I checked the status the most frequently downloaded crates:

crate | msrv
--- | ---
rand | 1.36
syn, quote | 1.31
libc | 1.13
bitflags | 1.20
serde | 1.13
log | 1.31
... | ...
serde_derive (!) | 1.31
tokio | 1.45

Then there's the Rust user survey results: https://blog.rust-lang.org/2020/12/16/rust-survey-2020.html#stability

And 1.34 is the [oldest rustc in Debian](https://packages.debian.org/de/jessie/rustc) ... usually pretty conservative.

There's a fair bit of controversy if and when bumping msrv is considered a breaking change: https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980

**Comment by niklasf** [comment]
Perhaps most convincing is that `cc` (a dependency in the fallback code!), now uses rustc 1.34 as the minimum supported Rust version: https://github.com/alexcrichton/cc-rs/commit/c668e9e4770fac31515fb999630c867e80efe2c0

**Comment by gz** [comment]
Perfect, in that case I think we can safely merge this.

**Pull request merged**
