### PR TITLE
Improve feature coverage of `ExtendedFeatures`

### PR DESCRIPTION
**Pull request by semiviral**
Adds support for all the missing bits in `ExtendedFeatures.ecx`. Additionally, all of the functions within the `ExtendedFeatures` impl are marked `const` and prefixed with `#[inline]` for better codegen at compile-time.

### CODE REVIEW

**Comment by gz** [comment]
Hi thanks, this looks aside from changing the emojis.
 
I'm curious about the reason for the `#[inline]` annotations, did you notice some slowdown in your code or is this based on some recommendation, personal experience? I can imagine there may be cases where it can hurt debugging (e.g., you're checking for some feature and then use it after and due to some bug it still crashes, if the function name appears in the backtrace it will help a developer point to the problem quickly whereas now this is gone (not a huge deal but something to consider maybe)).

**Comment by gz** [comment]
Also do you mind rebasing the commit on top of current master instead of the merge commit? I'd like to ensure a linear history for the project so currently it doesn't let me merge it because of github settings.

**Comment by semiviral** [comment]
> I'm curious about the reason for the `#[inline]` annotations, did you notice some slowdown in your code or is this based on some recommendation or personal experience? I can imagine there may be cases where it can hurt debugging (e.g., you're checking for some feature and then use it after and due to some bug it still crashes, if the function name appears in the backtrace it will help a developer point to the problem quickly whereas now this hint may be gone (not a huge deal but something to consider maybe)).

I don't believe there's any way the functions marked as inlineable can meaningfully fail, so the stack trace should almost never make it to the inside of these functions (if they weren't inlined), so I didn't see any harm. But, they aren't specifically necessary, so if you'd like me to remove the annotations I can.

> Also do you mind rebasing the commit on top of current master instead of the merge commit? I'd like to ensure a linear history for the project so currently it doesn't let me merge it because of github settings.

I believe this is done now. Evidently, I was many, *many* commits behind, haha.

**Comment by gz** [comment]
> I don't believe there's any way the functions I marked as inlineable can meaningfully fail, so the stack trace should almost never make it to the inside of these functions (if they weren't inlined); so I didn't see any harm. But, they aren't specifically necessary, so if you'd like me to remove the annotations I can.

No that seems fine to me we can keep it, was just curious about the change!

> I believe this is done now. Evidently, I was many, many commits behind, haha.

Thanks! Unfortunately github UI still tells me "This branch cannot be rebased due to conflicts" did something go wrong with the rebasing? May be easier to just checkout master and cherry pick your two commits on top of it again...

**Comment by gz** [comment]
Thanks for your contribution!

**Pull request closed without merging**
