### PR TITLE
Add amd_family_id and amd_model_id to FeatureInfo.

### PR DESCRIPTION
**Pull request by daym**
https://www.amd.com/system/files/TechDocs/25481.pdf

### CODE REVIEW

**Comment by daym** [comment]
See issue #26

**Comment by gz** [comment]
I think Intel is quite similar here:

```
The Extended Family ID needs to be examined only when the Family ID is 0FH. Integrate the fields into a display using the following rule:
IF Family_ID ≠ 0FH
THEN DisplayFamily = Family_ID;
ELSE DisplayFamily = Extended_Family_ID + Family_ID; (* Right justify and zero-extend 4-bit field. *)
FI;
(* Show DisplayFamily as HEX field. *)
The Extended Model ID needs to be examined only when the Family ID is 06H or 0FH. Integrate the field into a display using the following rule:
IF (Family_ID = 06H or Family_ID = 0FH)
THEN DisplayModel = (Extended_Model_ID « 4) + Model_ID;
(* Right justify and zero-extend 4-bit field; display Model_ID as HEX field.*) ELSE DisplayModel = Model_ID;
FI;
(* Show DisplayModel as HEX field. *)
```

so my plan is to change behavior of `model_id` and `family_id` function with major release v10 and rename the current `model_id` and `family_id` functions to `base_model_id` and `base_family_id`.

**Comment by daym** [comment]
That's even better!

**Comment by gz** [comment]
I addressed this in #55. Once this is ready and merged, you should be able to use family_id() and model_id() directly for querying this. 
Thanks anyways for the patch even though I didn't end up merging it. It made me aware of the model/family extra computation. Sorry I didn't merge it in before figuring out the rest needed for AMD support.

**Pull request closed without merging**
